import { Router } from 'express';
import { createStudent, deleteStudent, getStudentById, getStudents, getStats, updateStudent, updateStudentStatus, } from '../controllers/student.controller.js';
const router = Router();
router.get('/stats', getStats);
router.post('/', createStudent);
router.get('/', getStudents);
router.get('/:id', getStudentById);
router.put('/:id', updateStudent);
router.patch('/:id/status', updateStudentStatus);
router.delete('/:id', deleteStudent);
export default router;
